language: php

php:
  - 8.0

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist --optimize-autoloader --no-interaction
  - cp .env.dev .env

script:
  - php artisan test --parallel
